### ISSUE TITLE
Laravel 6.0 Support?

### ISSUE THREAD

**Issue by Unholny** [dannyvankooten/laravel-vat#16]
Hello. Laravel 6.0 has been released. Do you plan on supporting it?

**Comment by janyksteenbeek** [comment]
There's an open PR #15. Would be great if that one could be merged!

**Comment by Unholny** [comment]
Yeah, that would be great if we could finish this today, so we can start the week with a fresh 6.0 upgrade on all our clients' projects. @dannyvankooten

**Comment by dannyvankooten** [comment]
Thanks @janyksteenbeek, sorry for only seeing this now.

**Comment by Unholny** [comment]
@dannyvankooten I am sorry for re-opening this issue but I wanted to let you know that I cannot install this package with a simple:
_**composer require dannyvankooten/laravel-vat**_

Currently this fix is situated in the dev-master version of the Packagist.
https://packagist.org/packages/dannyvankooten/laravel-vat#dev-master

When do you plan on tagging it for Packagist? :)

**Comment by dannyvankooten** [comment]
@Unholny just tagged version `2.0.2` so you can switch to that version in your Composer deps. Cheers!

**Comment by JexPY** [comment]
Hello @dannyvankooten,

I have tried to update to laravel ^6.4 and I am getting

> Problem 1
    - Conclusion: remove dannyvankooten/laravel-vat 2.0.3
    - Conclusion: don't install dannyvankooten/laravel-vat 2.0.3
    - Conclusion: don't install dannyvankooten/laravel-vat 2.0.2
    - Conclusion: don't install dannyvankooten/laravel-vat 2.0.1
    - Conclusion: don't install laravel/framework v6.4.1
    - Installation request for dannyvankooten/laravel-vat ^2.0 -> satisfiable by dannyvankooten/laravel-vat[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - Conclusion: don't install laravel/framework v6.4.0

Please check the compatibility.
Thanks
