### ISSUE TITLE
Laravel 6.2 support

### ISSUE THREAD

**Issue by celcius-jochen** [dannyvankooten/laravel-vat#18]
Any chance a new release could be tagged with support for Laravel 6.2?

**Comment by marijnbent** [comment]
Would be nice! Should I make a pull request or can you do it @dannyvankooten?

**Comment by dannyvankooten** [comment]
PR please. Not really using Laravel myself and their release schedule is a little.... aggressive. :sweat_smile: Will merge quickly though!

**Comment by marijnbent** [comment]
You are quick to reply 🤓! Do you agree 6.* is the way to go for the new semantic versioning?

**Comment by dannyvankooten** [comment]
It would sure be easier but I'm not sure about Laravel's compatibility promise? I'd say let's err on the safe side and keep things explicit, in case 6.3 or later introduces a breaking change in the code this library relies upon.

**Comment by celcius-jochen** [comment]
Hate to break the news, but Laravel is about to release v6.3 😅😅😅
https://github.com/laravel/framework/releases
