### ISSUE TITLE
VAT provider jsonvat.com discontinued

### ISSUE THREAD

**Issue by Vladelis** [dannyvankooten/laravel-vat#26]
Since jsonvat.com is discontinued will the library migrate to another vat provider or cease working with it?

**Comment by dannyvankooten** [comment]
Hello @Vladelis,

Sorry, only seeing this now. The actual logic lives in [ibericode/vat](https://github.com/ibericode/vat) which already has support for different providers like [ibericode/vat-rates](https://github.com/ibericode/vat-rates) (which it uses as the default).

I recommend watching the latter repository and submitting pull requests whenever you notice a rate change for your country, so we can keep it updated together. Github takes care of hosting it for us, so we don't have to worry about downtimes as much as with jsonvat.com. 😃
