### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by SlyDave** [dannyvankooten/laravel-vat#34]
Pull request already created for it by @LKaemmerling - https://github.com/dannyvankooten/laravel-vat/pull/31

**Comment by anzalpa** [comment]
Hi,

**Comment by LKaemmerling** [comment]
@anzalpa my change/MR was merged but not released/tagged. Therefore you can't install it with the version, try to use master.

**Comment by dannyvankooten** [comment]
> @anzalpa my change/MR was merged but not released/tagged. Therefore you can't install it with the version, try to use master.

Whoops. Addressed!
